version: '3'
services: 
    web:
        build: .
        ports:
        - 8080:8080
    db:
        image: mysql
        ports: 
            - 3309:3306
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: library
            MYSQL_USER: library
            MYSQL_PASSWORD: library
